pandoc -o html\toc.html txt\toc.txt
pandoc -o html\chapter01.html txt\chapter01.txt
pandoc -o html\chapter02.html txt\chapter02.txt
pandoc -o html\chapter03.html txt\chapter03.txt
pandoc -o html\chapter04.html txt\chapter04.txt
pandoc -o html\chapter05.html txt\chapter05.txt
pandoc -o html\chapter06.html txt\chapter06.txt
pandoc -o html\chapter07.html txt\chapter07.txt
pandoc -o html\chapter08.html txt\chapter08.txt
pandoc -o html\chapter09.html txt\chapter09.txt
pandoc -o html\chapter10.html txt\chapter10.txt
pandoc -o html\chapter11.html txt\chapter11.txt
pandoc -o html\chapter12.html txt\chapter12.txt
pandoc -o html\chapter13.html txt\chapter13.txt
pandoc -o html\chapter14.html txt\chapter14.txt
pandoc -o html\chapter15.html txt\chapter15.txt